project:
  type: website
  output-dir: docs

website:
  title: "Programación literaria con R"
  lang: es
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - preparacion.qmd
      - text: "Ejemplos"
        menu:
          - quarto_reporte_ejemplo.qmd
          - rmarkdown_reporte_ejemplo.Rmd
      - text: "Materiales"
        menu:
          - 01_presentacion.qmd
          - 02_reportes.qmd
          - 03_sintaxis.qmd
          - 04_proyectos.qmd
          - 05_trabajo.qmd
          - 06_parametrizacion.qmd
          - 07_plantillas.qmd
          - 08_publicacion.qmd

format:
  html:
    theme: 
      - united
      - custom.scss
    css: styles.css
    toc: true

editor: visual

